/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  AppUser,
  GetUserByEmailParams
} from '.././models'
import { customInstance } from '.././mutator/custom-instance';


// eslint-disable-next-line
  type SecondParameter<T extends (...args: any) => any> = T extends (
  config: any,
  args: infer P,
) => any
  ? P
  : never;


  export const addUser = (
    appUser: AppUser,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<AppUser>(
      {url: `/users/add`, method: 'post',
      headers: {'Content-Type': 'application/json', },
      data: appUser
    },
      options);
    }
  export const getUsers = (
    
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<AppUser[]>(
      {url: `/users`, method: 'get'
    },
      options);
    }
  export const getUserByUUID = (
    uuid: string,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<AppUser>(
      {url: `/users/user/${uuid}`, method: 'get'
    },
      options);
    }
  export const getUserByEmail = (
    params: GetUserByEmailParams,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<AppUser>(
      {url: `/users/getByEmail`, method: 'get',
        params
    },
      options);
    }
  export type AddUserResult = NonNullable<Awaited<ReturnType<typeof addUser>>>
export type GetUsersResult = NonNullable<Awaited<ReturnType<typeof getUsers>>>
export type GetUserByUUIDResult = NonNullable<Awaited<ReturnType<typeof getUserByUUID>>>
export type GetUserByEmailResult = NonNullable<Awaited<ReturnType<typeof getUserByEmail>>>
