/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  rest
} from 'msw'
import {
  faker
} from '@faker-js/faker'

export const getFindSanitizableMock = () => (Array.from({ length: faker.datatype.number({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({segmentIndex: faker.helpers.arrayElement([faker.datatype.number({min: undefined, max: undefined}), undefined]), segmentContent: faker.helpers.arrayElement([faker.random.word(), undefined]), segmentType: faker.helpers.arrayElement([faker.random.word(), undefined])})))

export const getTaggerControllerMSW = () => [
rest.post('*/tagger/find-sanitizable', (_req, res, ctx) => {
        return res(
          ctx.delay(1000),
          ctx.status(200, 'Mocked status'),
ctx.json(getFindSanitizableMock()),
        )
      }),]
