/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  Segment
} from '.././models'
import { customInstance } from '.././mutator/custom-instance';


// eslint-disable-next-line
  type SecondParameter<T extends (...args: any) => any> = T extends (
  config: any,
  args: infer P,
) => any
  ? P
  : never;


  export const findSanitizable = (
    findSanitizableBody: string,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<Segment[]>(
      {url: `/tagger/find-sanitizable`, method: 'post',
      headers: {'Content-Type': 'application/json', },
      data: findSanitizableBody
    },
      options);
    }
  export type FindSanitizableResult = NonNullable<Awaited<ReturnType<typeof findSanitizable>>>
