/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { AppUserService } from './appUserService';

export interface ChatQueryDTO {
  timestamp: string;
  id: string;
  queryContent: string;
  sanitizedQueryContent: string;
  userService?: AppUserService;
}
