/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface Segment {
  segmentIndex?: number;
  segmentContent?: string;
  segmentType?: string;
}
