/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  ChatQueryDTO,
  ChatQuery,
  FetchDatabaseSubsetParams
} from '.././models'
import { customInstance } from '.././mutator/custom-instance';


// eslint-disable-next-line
  type SecondParameter<T extends (...args: any) => any> = T extends (
  config: any,
  args: infer P,
) => any
  ? P
  : never;


  export const addLogToDatabase = (
    chatQueryDTO: ChatQueryDTO,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<void>(
      {url: `/audit/add-log`, method: 'post',
      headers: {'Content-Type': 'application/json', },
      data: chatQueryDTO
    },
      options);
    }
  export const fetchDatabase = (
    
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<ChatQuery[]>(
      {url: `/audit/get-logs`, method: 'get'
    },
      options);
    }
  export const fetchDatabaseSubset = (
    params: FetchDatabaseSubsetParams,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<ChatQuery[]>(
      {url: `/audit/get-logs-between`, method: 'get',
        params
    },
      options);
    }
  export type AddLogToDatabaseResult = NonNullable<Awaited<ReturnType<typeof addLogToDatabase>>>
export type FetchDatabaseResult = NonNullable<Awaited<ReturnType<typeof fetchDatabase>>>
export type FetchDatabaseSubsetResult = NonNullable<Awaited<ReturnType<typeof fetchDatabaseSubset>>>
